# Power Query M — paste into Advanced Editor after changing the CSV path

let
    Source = Csv.Document(File.Contents("C:\YOUR_PATH\hr_employee_data.csv"),
        [Delimiter=",", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders,{
        {"Employee ID", type text},{"Age", Int64.Type},{"Gender", type text},
        {"Marital Status", type text},{"Education", type text},{"Department", type text},
        {"Job Role", type text},{"Years at Company", Int64.Type},{"Monthly Income", Int64.Type},
        {"Job Satisfaction", Int64.Type},{"Environment Satisfaction", Int64.Type},
        {"Overtime", type text},{"Business Travel", type text},{"Attrition", type text}}),
    RemovedBlankRows = Table.SelectRows(ChangedTypes, each [Employee ID] <> null and [Employee ID] <> ""),
    RemovedDuplicates = Table.Distinct(RemovedBlankRows, {"Employee ID"})
in
    RemovedDuplicates
